version: 2.1
executors: 
  docker-publisher:
    environment:
      IMAGE_TAG: zyr54/tp_node_docker_circleci:latest
    docker: 
      - image: docker:stable

jobs:
  build_docker:
    executor: docker-publisher
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build . -t node_example
      - run: |
          docker run -d --name node_example node_example
          docker run --network container:node_example appropriate/curl --retry 10 --retry-connrefused http://localhost:8080
      - persist_to_workspace:
          root: .
          paths: 
            - ./image.tar

  push_docker:
    executor: docker-publisher
    docker:
      - image: cimg/base:2022.05
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load --input /tmp/workspace/image.tar
      - run: echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
      - run: docker push "${IMAGE_TAG}"

workflows:
  launching:
    jobs:
      - build_docker
      - push_docker