version: 2.1
executors: 
  docker-publisher:
    environment:
      IMAGE_TAG: zyr54/tp_node_docker_circleci
    docker: 
      - image: circleci/buildpack-deps:stretch

jobs:
  build_docker:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build . -t "$IMAGE_TAG"
      - run: |
          docker run -d --name node_example "$IMAGE_TAG"
          docker run --network container:node_example appropriate/curl --retry 10 --retry-connrefused http://localhost:8080
      - run: docker save -o image.tar "$IMAGE_TAG"
      - persist_to_workspace:
          root: .
          paths: 
            - ./image.tar

  push_docker:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load -i /tmp/workspace/image.tar
      - run: echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
      - run: docker push "$IMAGE_TAG"

workflows:
  version: 2
  launching:
    jobs:
      - build_docker:
          filters:
              branches:
                only: master
      - push_docker:
          requires:
            - build_docker
          filters:
            branches:
              only: master