version: 2.1

jobs:
  build_docker:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build . -t node_example
      - run: |
          ssh remote-docker \ curl localhost:8080

workflows:
  launching:
    jobs:
      - build_docker